version: '3'
services:
  ipfs:
    image: ipfs/go-ipfs:latest
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/ipfsdata
    volumes:
      - ./data/ipfs:/ipfsdata
    ports:
    - "5001:5001"
    - "4001:4001"
    - "8080:8080"



  frontend:
    build: frontend
    ports:
      - "3000:3000"
  