name: price_prophet
author: ethlisbon
version: 0.1.0
description: A simple demonstration of a simple ABCI application
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint: {}
fingerprint_ignore_patterns: []
agent: ethlisbon/price_prophet:0.1.0:bafybeibrddzmw3y56kkh7v66nif5dmphzuxr4bbmqv7euqzpnms2rzn4qq
number_of_agents: 4
---
params:
  args: &id001
    setup:
      safe_contract_address:
      - '0xd87bEe9DDD28773ac2EBEE70AE005F2DeB46B400'
      oracle_contract_address:
      - '0xACF6F2b3dfCC96DcE5BdFFC422cbDd3b179727db'
public_id: ethlisbon/price_prophet:0.1.0
type: skill
models:
  0:
  - params:
      args: *id001
  1:
  - params:
      args: *id001
  2:
  - params:
      args: *id001
  3:
  - params:
      args: *id001
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${CHAIN_RPC:str:http://host.docker.internal:8545}
      chain_id: ${CHAIN_ID:int:31337}
      poa_chain: false
      default_gas_price_strategy: eip1559
